[project]
name = "llamachat-backend"
version = "0.2.0"
description = "My custom llama-stack distribution descriptor file"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "chardet>=7.1.0",
  "faiss-cpu>=1.13.2",
  "ogx==0.8.0",
  "ogx-api==0.8.0",
  "ollama>=0.6.1",
  "pymilvus[milvus-lite]>=3.0.0",
  "pypdf>=6.9.0",
  "torch>=2.10.0",
]
